package me.kay.entity.sys;

import javax.persistence.Id;
import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sys_permission
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class SysOperator implements Serializable {

    private static final long serialVersionUID = 1L;

    @Id
    private int operator_id;
    private String operator_name;
    private String operator_url;
    private int operator_state;
    private int menu_id;
    private int permission_id;

    public SysOperator() {
    }

    public SysOperator(int operator_id, String operator_name, String operator_url, int operator_state, int menu_id, int permission_id) {
        this.operator_id = operator_id;
        this.operator_name = operator_name;
        this.operator_url = operator_url;
        this.operator_state = operator_state;
        this.menu_id = menu_id;
        this.permission_id = permission_id;
    }

    public int getOperator_id() {
        return operator_id;
    }

    public void setOperator_id(int operator_id) {
        this.operator_id = operator_id;
    }

    public String getOperator_name() {
        return operator_name;
    }

    public void setOperator_name(String operator_name) {
        this.operator_name = operator_name;
    }

    public String getOperator_url() {
        return operator_url;
    }

    public void setOperator_url(String operator_url) {
        this.operator_url = operator_url;
    }

    public int getOperator_state() {
        return operator_state;
    }

    public void setOperator_state(int operator_state) {
        this.operator_state = operator_state;
    }

    public int getMenu_id() {
        return menu_id;
    }

    public void setMenu_id(int menu_id) {
        this.menu_id = menu_id;
    }

    public int getPermission_id() {
        return permission_id;
    }

    public void setPermission_id(int permission_id) {
        this.permission_id = permission_id;
    }

    @Override
    public String toString() {
        return "SysOperator{" +
                "operator_id=" + operator_id +
                ", operator_name='" + operator_name + '\'' +
                ", operator_url='" + operator_url + '\'' +
                ", operator_state=" + operator_state +
                ", menu_id=" + menu_id +
                ", permission_id=" + permission_id +
                '}';
    }
}