package me.kay.entity.sys;

import javax.persistence.Id;
import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sys_permission
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class SysPermission implements Serializable {

    private static final long serialVersionUID = 1L;

    @Id
    private int permissionId;
    private String permissionCode;
    private String permissionType;

    public SysPermission() {
    }

    public SysPermission(int permissionId, String permissionCode, String permissionType) {
        this.permissionId = permissionId;
        this.permissionCode = permissionCode;
        this.permissionType = permissionType;
    }

    public int getPermissionId() {
        return permissionId;
    }

    public void setPermissionId(int permissionId) {
        this.permissionId = permissionId;
    }

    public String getPermissionCode() {
        return permissionCode;
    }

    public void setPermissionCode(String permissionCode) {
        this.permissionCode = permissionCode;
    }

    public String getPermissionType() {
        return permissionType;
    }

    public void setPermissionType(String permissionType) {
        this.permissionType = permissionType;
    }

    @Override
    public String toString() {
        return "SysPermission{" +
                "permissionId=" + permissionId +
                ", permissionCode='" + permissionCode + '\'' +
                ", permissionType='" + permissionType + '\'' +
                '}';
    }
}